# Docker Deployment Configuration for Render
# This ensures we use Python 3.10 via Docker (guaranteed compatibility)

services:
  - type: web
    name: loan-sanctioning-system
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: loan-ml-secret-key-2024
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /